name: lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: '1.1.265'
          warnings: false
