name: lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: Run Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: '1.1.286'
          warnings: false
